# Generated by Django 6.1 on 2026-08-12 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('service_kind', models.CharField(choices=[('REGISTRATION', 'Registration'), ('COMPLIANCE', 'Compliance'), ('CERTIFICATION', 'Certification'), ('GOVT_SCHEME', 'Government Scheme'), ('GRANT', 'Grant'), ('LOAN', 'Loan'), ('DEBT', 'Debt Funding'), ('EQUITY', 'Equity Funding'), ('VC', 'VC Funding'), ('SUBSIDY', 'Subsidy'), ('LEGAL', 'Legal Service'), ('DIGITAL', 'Digital Service'), ('CONSULTING', 'Consulting'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('EXPIRING', 'Expiring'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('bde_summary', models.TextField(blank=True, help_text='Short explanation BDE can quickly read during a call.')),
                ('overview', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('important_notes', models.TextField(blank=True)),
                ('eligibility_summary', models.TextField(blank=True)),
                ('business_types', models.JSONField(blank=True, default=list)),
                ('business_stages', models.JSONField(blank=True, default=list)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('applicable_states', models.JSONField(blank=True, default=list)),
                ('founder_categories', models.JSONField(blank=True, default=list)),
                ('min_business_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('max_business_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('min_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('max_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('funding_min', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('funding_max', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('funding_type', models.CharField(blank=True, max_length=120)),
                ('interest_rate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('interest_rate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('collateral_required', models.BooleanField(blank=True, null=True)),
                ('tenure', models.CharField(blank=True, max_length=150)),
                ('subsidy_details', models.TextField(blank=True)),
                ('government_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bharatnxt_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_notes', models.TextField(blank=True)),
                ('estimated_processing_time', models.CharField(blank=True, max_length=150)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('sales_pitch', models.TextField(blank=True)),
                ('escalation_notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='toolkit.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_services', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='toolkit.servicedomain')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('DISQUALIFIER', 'Disqualifier'), ('INFORMATION', 'Information')], default='REQUIRED', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='toolkit.service')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='toolkit.service')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='toolkit.servicedomain'),
        ),
        migrations.CreateModel(
            name='ServiceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('is_official', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='toolkit.service')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('PREREQUISITE', 'Prerequisite'), ('ALTERNATIVE', 'Alternative'), ('FOLLOW_UP', 'Follow-up Service')], default='RECOMMENDED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='toolkit.service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='toolkit.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'related_service', 'relation_type'), name='unique_service_relationship')],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_time', models.CharField(blank=True, max_length=120)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='toolkit.service')),
            ],
            options={
                'ordering': ['step_number'],
                'constraints': [models.UniqueConstraint(fields=('service', 'step_number'), name='unique_step_number_per_service')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='toolkit_ser_status_ba8727_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_kind'], name='toolkit_ser_service_ddf76e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['domain'], name='toolkit_ser_domain__030283_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='toolkit_ser_categor_b0529e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['updated_at'], name='toolkit_ser_updated_8c4271_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['last_verified_at'], name='toolkit_ser_last_ve_128a05_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('domain', 'slug'), name='unique_category_slug_per_domain'),
        ),
    ]
