# Generated by Django 6.1 on 2026-08-13 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('XLSX', 'Excel'), ('CSV', 'CSV'), ('GOOGLE_SHEET', 'Google Sheet')], max_length=30)),
                ('source_name', models.CharField(max_length=255)),
                ('source_identifier', models.CharField(blank=True, max_length=500)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sheet_count', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toolkit_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'created_at'], name='toolkit_imp_source__c1009c_idx'), models.Index(fields=['status', 'created_at'], name='toolkit_imp_status_48c770_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='toolkit.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_toolkit_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='toolkit_sav_user_id_b88b7d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='unique_saved_service_per_user')],
            },
        ),
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SEARCH', 'Search'), ('SUGGESTION_CLICK', 'Suggestion Click'), ('FILTER', 'Filter'), ('CLIENT_MATCH', 'Client Match')], default='SEARCH', max_length=30)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('selected_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_selections', to='toolkit.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_search_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='toolkit_sea_user_id_aa6e0a_idx'), models.Index(fields=['event_type', 'created_at'], name='toolkit_sea_event_t_84b366_idx')],
            },
        ),
    ]
