# Generated by Django 6.1 on 2026-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0002_importbatch_savedservice_searchevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Date from which BDEs should start pitching this service.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pitch_until',
            field=models.DateField(blank=True, db_index=True, help_text='Internal last date until which BDEs should pitch this service.', null=True),
        ),
    ]
