# Generated by Django 6.1 on 2026-08-14 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_service_effective_from_service_pitch_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toolkit_rolled_back_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='applicable_for_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='application_deadline_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='deadline_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('DATED', 'Specific Date'), ('ROLLING', 'Rolling'), ('ONGOING', 'Ongoing'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('NO_DEADLINE', 'No Deadline'), ('OTHER', 'Other')], db_index=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='funding_organisation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicesource',
            name='source_kind',
            field=models.CharField(choices=[('OFFICIAL_PORTAL', 'Official Portal'), ('APPLICATION', 'Application Link'), ('FLYER', 'Flyer'), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], db_index=True, default='REFERENCE', max_length=30),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PREVIEWED', 'Previewed'), ('VALIDATED', 'Validated'), ('IMPORTING', 'Importing'), ('IMPORTED', 'Imported'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicesource',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('BDE', 'BDE')], db_index=True, default='ADMIN_ONLY', max_length=20)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_templates', to='toolkit.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_matrices', to='toolkit.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(db_index=True, max_length=255)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('WARNING', 'Warning'), ('INVALID', 'Invalid'), ('PROCESSED', 'Processed')], db_index=True, default='PENDING', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('candidate_action', models.CharField(choices=[('UNDECIDED', 'Undecided'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('MERGE_REVIEW', 'Merge Review'), ('SKIP', 'Skip'), ('INVALID', 'Invalid')], db_index=True, default='UNDECIDED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='toolkit.importbatch')),
                ('imported_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_source_rows', to='toolkit.service')),
                ('matched_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_import_rows', to='toolkit.service')),
            ],
            options={
                'ordering': ['import_batch', 'sheet_name', 'source_row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SERVICE_CREATE', 'Service Create'), ('SERVICE_UPDATE', 'Service Update'), ('CLASSIFICATION_ADD', 'Classification Add'), ('SOURCE_ADD', 'Source Add'), ('COMMERCIAL_CREATE', 'Commercial Create'), ('COMMERCIAL_UPDATE', 'Commercial Update'), ('CONTENT_CREATE', 'Content Create'), ('REFERENCE_CREATE', 'Reference Create'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='toolkit.importbatch')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_changes', to='toolkit.service')),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='toolkit.importrow')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('row_label', models.CharField(blank=True, max_length=255)),
                ('value_raw', models.TextField(blank=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_entries', to='toolkit.service')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='toolkit.comparisonmatrix')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_entries', to='toolkit.importrow')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='servicesource',
            name='import_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_sources', to='toolkit.importrow'),
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(db_index=True, max_length=150)),
                ('key', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('BDE', 'BDE')], db_index=True, default='ADMIN_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_items', to='toolkit.importrow')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_classification_links', to='toolkit.category')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_links', to='toolkit.service')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classifications', to='toolkit.importrow')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='classifications',
            field=models.ManyToManyField(blank=True, related_name='classified_services', through='toolkit.ServiceClassification', to='toolkit.category'),
        ),
        migrations.CreateModel(
            name='ServiceCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('minimum_charge_raw', models.TextField(blank=True)),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('government_fee_raw', models.TextField(blank=True)),
                ('government_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vendor_cost_raw', models.TextField(blank=True)),
                ('vendor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bdm_deduction_raw', models.TextField(blank=True)),
                ('bdm_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('BDE_ALLOWED', 'BDE Allowed')], db_index=True, default='ADMIN_ONLY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_terms', to='toolkit.service')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_terms', to='toolkit.importrow')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('OVERVIEW', 'Overview'), ('BENEFITS', 'Benefits'), ('ELIGIBILITY', 'Eligibility'), ('FUNDING', 'Funding'), ('SCOPE', 'Scope of Work'), ('PROCESS', 'Process'), ('DOCUMENTS', 'Documents'), ('TIMELINE', 'Timeline'), ('NOTES', 'Notes'), ('GLOSSARY', 'Glossary'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('BDE', 'BDE')], db_index=True, default='ADMIN_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='toolkit.service')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_sections', to='toolkit.importrow')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['import_batch', 'validation_status'], name='toolkit_imp_import__019aff_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['import_batch', 'candidate_action'], name='toolkit_imp_import__4e6039_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'sheet_name', 'source_row_number'), name='unique_import_row_per_sheet'),
        ),
        migrations.AddConstraint(
            model_name='comparisonentry',
            constraint=models.UniqueConstraint(fields=('matrix', 'row_number', 'column_name'), name='unique_comparison_matrix_cell'),
        ),
        migrations.AddConstraint(
            model_name='serviceclassification',
            constraint=models.UniqueConstraint(fields=('service', 'category'), name='unique_service_classification'),
        ),
    ]
