# Generated by Django 6.1 on 2026-08-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_workbook_import_architecture_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='importchange',
            name='object_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='importchange',
            name='object_pk',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='importrow',
            name='import_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source_sheet', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('BDE', 'BDE')], db_index=True, default='ADMIN_ONLY', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='toolkit.importbatch')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('OVERVIEW', 'Overview'), ('BENEFITS', 'Benefits'), ('ELIGIBILITY', 'Eligibility'), ('FUNDING', 'Funding'), ('SCOPE', 'Scope of Work'), ('PROCESS', 'Process'), ('DOCUMENTS', 'Documents'), ('TIMELINE', 'Timeline'), ('NOTES', 'Notes'), ('GLOSSARY', 'Glossary'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_heading', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('BDE', 'BDE')], db_index=True, default='ADMIN_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='toolkit.knowledgedocument')),
                ('linked_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_sections', to='toolkit.service')),
                ('source_import_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_section', to='toolkit.importrow')),
            ],
            options={
                'ordering': ['document', 'display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('document', 'display_order'), name='unique_knowledge_section_order_per_document')],
            },
        ),
    ]
