# Generated by Django 6.1 on 2026-08-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_final_import_knowledge_architecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_saved_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='toolkit.savedcollection')),
                ('saved_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='toolkit.savedservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedcollection',
            index=models.Index(fields=['user', 'updated_at'], name='toolkit_sav_user_id_16a817_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcollection',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_saved_collection_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='savedcollectionitem',
            index=models.Index(fields=['collection', 'created_at'], name='toolkit_sav_collect_895ec4_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'saved_service'), name='unique_saved_service_per_collection'),
        ),
    ]
