# Generated by Django 6.1 on 2026-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0007_service_flyers_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PREVIEWED', 'Previewed'), ('VALIDATED', 'Validated'), ('QUEUED', 'Queued for import'), ('IMPORTING', 'Importing'), ('IMPORTED', 'Imported'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=30),
        ),
    ]
