# Generated by Django 6.1 on 2026-08-13 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EMPLOYEE_CREATE', 'Employee Created'), ('EMPLOYEE_EDIT', 'Employee Updated'), ('EMPLOYEE_ACTIVATE', 'Employee Activated'), ('EMPLOYEE_DEACTIVATE', 'Employee Deactivated'), ('PASSWORD_RESET', 'Password Reset'), ('SEARCH', 'Toolkit Search'), ('FILTER', 'Toolkit Filter'), ('SERVICE_VIEW', 'Service Viewed'), ('IMPORT', 'Data Import'), ('PERMISSION_DENIED', 'Permission Denied')], max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
