# Generated by Django 6.1 on 2026-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Sign-in Failed'), ('LOGIN_BLOCKED', 'Sign-in Blocked'), ('LOGOUT', 'Logout'), ('EMPLOYEE_CREATE', 'Employee Created'), ('EMPLOYEE_EDIT', 'Employee Updated'), ('EMPLOYEE_ACTIVATE', 'Employee Activated'), ('EMPLOYEE_DEACTIVATE', 'Employee Deactivated'), ('PASSWORD_RESET', 'Password Reset'), ('SEARCH', 'Toolkit Search'), ('FILTER', 'Toolkit Filter'), ('SERVICE_VIEW', 'Service Viewed'), ('IMPORT', 'Data Import'), ('PERMISSION_DENIED', 'Permission Denied')], max_length=40),
        ),
    ]
