"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rsje19v)%tk@*b-n93v&u=eu5-izbj($bdz7n0h138-s@kpstl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "accounts",
    "dashboard",
    "toolkit",
]

MIDDLEWARE = [
    "accounts.network_security.OfficeNetworkMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "accounts.portal_access.AdminPortalAccessMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTH_USER_MODEL = "accounts.User"

# Authentication
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# =========================================================
# OFFICE NETWORK SECURITY
# =========================================================
#
# Development:
# False = localhost works normally.
#
# Production:
# Change OFFICE_NETWORK_ENFORCED to True and replace/add
# the real BharatNXT office LAN subnet.
#
OFFICE_NETWORK_ENFORCED = False

OFFICE_ALLOWED_NETWORKS = [
    "127.0.0.1/32",
    "::1/128",
]


# =========================================================
# BHARATNXT PRODUCTION CONFIGURATION
# =========================================================

import os


# ---------------------------------------------------------
# Regional settings
# ---------------------------------------------------------

TIME_ZONE = "Asia/Kolkata"
USE_TZ = True


# ---------------------------------------------------------
# Environment-driven security
# ---------------------------------------------------------

ENVIRONMENT = os.environ.get(
    "BHARATNXT_ENVIRONMENT",
    "development"
).lower()

IS_PRODUCTION = ENVIRONMENT == "production"

if IS_PRODUCTION:
    SECRET_KEY = os.environ["BHARATNXT_SECRET_KEY"]

    DEBUG = False

    ALLOWED_HOSTS = [
        host.strip()
        for host in os.environ.get(
            "BHARATNXT_ALLOWED_HOSTS",
            ""
        ).split(",")
        if host.strip()
    ]

    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get(
            "BHARATNXT_CSRF_TRUSTED_ORIGINS",
            ""
        ).split(",")
        if origin.strip()
    ]

    OFFICE_NETWORK_ENFORCED = True

    OFFICE_ALLOWED_NETWORKS = [
        network.strip()
        for network in os.environ.get(
            "BHARATNXT_OFFICE_NETWORKS",
            ""
        ).split(",")
        if network.strip()
    ]


# ---------------------------------------------------------
# Session security
# ---------------------------------------------------------

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# ---------------------------------------------------------
# Browser security
# ---------------------------------------------------------

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"

SECURE_REFERRER_POLICY = "same-origin"


# ---------------------------------------------------------
# HTTPS-only settings for production
# ---------------------------------------------------------

if IS_PRODUCTION:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_SSL_REDIRECT = True

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https"
    )


# ---------------------------------------------------------
# Database
#
# Development:
# SQLite remains simple and local.
#
# Production:
# PostgreSQL credentials come entirely from environment.
# ---------------------------------------------------------

DATABASE_ENGINE = os.environ.get(
    "BHARATNXT_DB_ENGINE",
    "sqlite"
).lower()

if DATABASE_ENGINE == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["BHARATNXT_DB_NAME"],
            "USER": os.environ["BHARATNXT_DB_USER"],
            "PASSWORD": os.environ["BHARATNXT_DB_PASSWORD"],
            "HOST": os.environ.get(
                "BHARATNXT_DB_HOST",
                "127.0.0.1"
            ),
            "PORT": os.environ.get(
                "BHARATNXT_DB_PORT",
                "5432"
            ),
            "CONN_MAX_AGE": 60,
        }
    }


# Trusted reverse proxy addresses.
# Only these hosts may provide X-Real-IP.
TRUSTED_PROXY_IPS = [
    "127.0.0.1",
    "::1",
]

if IS_PRODUCTION:
    TRUSTED_PROXY_IPS = [
        ip.strip()
        for ip in os.environ.get(
            "BHARATNXT_TRUSTED_PROXIES",
            "127.0.0.1,::1"
        ).split(",")
        if ip.strip()
    ]
