"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# Development fallback only. Production reads BHARATNXT_SECRET_KEY from the
# environment (see the production block below) and refuses to start without it.
SECRET_KEY = os.environ.get(
    "BHARATNXT_SECRET_KEY",
    "django-insecure-development-only-key-never-use-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "accounts",
    "dashboard",
    "toolkit",
]

MIDDLEWARE = [
    "accounts.network_security.OfficeNetworkMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files directly from the app process. Needed on
    # platforms with no separate web server in front (Render); harmless when
    # nginx is serving /static/ itself, because nginx answers first.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "accounts.portal_access.AdminPortalAccessMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Destination for `manage.py collectstatic`. Nginx serves this directory
# directly (see deployment/nginx.internal.example); on a managed platform
# WhiteNoise serves it from inside the app process instead.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Compressed + hashed filenames, so static assets can be cached hard and a
# deploy busts the cache by itself. Every {% static %} reference in the
# templates was verified to resolve, which is what this storage requires.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTH_USER_MODEL = "accounts.User"

# Authentication
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# =========================================================
# OFFICE NETWORK SECURITY
# =========================================================
#
# Development:
# False = localhost works normally.
#
# Production:
# Change OFFICE_NETWORK_ENFORCED to True and replace/add
# the real BharatNXT office LAN subnet.
#
OFFICE_NETWORK_ENFORCED = False

OFFICE_ALLOWED_NETWORKS = [
    "127.0.0.1/32",
    "::1/128",
]


# =========================================================
# BHARATNXT PRODUCTION CONFIGURATION
# =========================================================


# ---------------------------------------------------------
# Regional settings
# ---------------------------------------------------------

TIME_ZONE = "Asia/Kolkata"
USE_TZ = True


# ---------------------------------------------------------
# Environment-driven security
# ---------------------------------------------------------

ENVIRONMENT = os.environ.get(
    "BHARATNXT_ENVIRONMENT",
    "development"
).lower()

IS_PRODUCTION = ENVIRONMENT == "production"

if IS_PRODUCTION:
    SECRET_KEY = os.environ["BHARATNXT_SECRET_KEY"]

    DEBUG = False

    ALLOWED_HOSTS = [
        host.strip()
        for host in os.environ.get(
            "BHARATNXT_ALLOWED_HOSTS",
            ""
        ).split(",")
        if host.strip()
    ]

    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get(
            "BHARATNXT_CSRF_TRUSTED_ORIGINS",
            ""
        ).split(",")
        if origin.strip()
    ]

    # Render publishes the service's own hostname. Adding it automatically
    # avoids the most common managed-platform deploy failure, where the app
    # boots fine and then rejects every request with DisallowedHost.
    _render_host = os.environ.get(
        "RENDER_EXTERNAL_HOSTNAME",
        "",
    ).strip()

    if _render_host:
        if _render_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_render_host)

        _render_origin = f"https://{_render_host}"

        if _render_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_render_origin)

    OFFICE_NETWORK_ENFORCED = True

    OFFICE_ALLOWED_NETWORKS = [
        network.strip()
        for network in os.environ.get(
            "BHARATNXT_OFFICE_NETWORKS",
            ""
        ).split(",")
        if network.strip()
    ]


# ---------------------------------------------------------
# Session security
# ---------------------------------------------------------

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# ---------------------------------------------------------
# Browser security
# ---------------------------------------------------------

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"

SECURE_REFERRER_POLICY = "same-origin"


# ---------------------------------------------------------
# HTTPS-only settings for production
# ---------------------------------------------------------

if IS_PRODUCTION:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_SSL_REDIRECT = True

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https"
    )


# ---------------------------------------------------------
# Database
#
# Development:
# SQLite remains simple and local.
#
# Production:
# PostgreSQL credentials come entirely from environment.
# ---------------------------------------------------------

# A single DATABASE_URL wins over the individual variables. Managed
# platforms (Render, Heroku, Fly) inject their database this way.
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "",
).strip()

if DATABASE_URL:
    _parsed = urlparse(DATABASE_URL)

    if _parsed.scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured(
            f"DATABASE_URL must be a PostgreSQL URL, got "
            f"scheme {_parsed.scheme!r}."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(_parsed.path.lstrip("/")),
            "USER": unquote(_parsed.username or ""),
            "PASSWORD": unquote(_parsed.password or ""),
            "HOST": _parsed.hostname or "127.0.0.1",
            "PORT": str(_parsed.port or "5432"),
            "CONN_MAX_AGE": 60,
        }
    }

    DATABASE_ENGINE = "postgresql"

else:
    DATABASE_ENGINE = os.environ.get(
        "BHARATNXT_DB_ENGINE",
        "sqlite"
    ).lower()

if DATABASE_ENGINE == "postgresql" and not DATABASE_URL:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["BHARATNXT_DB_NAME"],
            "USER": os.environ["BHARATNXT_DB_USER"],
            "PASSWORD": os.environ["BHARATNXT_DB_PASSWORD"],
            "HOST": os.environ.get(
                "BHARATNXT_DB_HOST",
                "127.0.0.1"
            ),
            "PORT": os.environ.get(
                "BHARATNXT_DB_PORT",
                "5432"
            ),
            "CONN_MAX_AGE": 60,
        }
    }


# ---------------------------------------------------------
# How the client IP is resolved
#
# "xrealip"   self-hosted nginx (default). X-Real-IP is
#             honoured only from TRUSTED_PROXY_IPS below.
#
# "forwarded" managed platform such as Render, where
#             REMOTE_ADDR is an internal platform address.
#             The client comes from X-Forwarded-For,
#             counting TRUSTED_PROXY_HOPS in from the right.
#
# This feeds the office-network allow-list, so getting it
# wrong either locks everyone out or makes the allow-list
# spoofable. See accounts/network_security.py.
# ---------------------------------------------------------

PROXY_MODE = os.environ.get(
    "BHARATNXT_PROXY_MODE",
    "xrealip",
).strip().lower()

TRUSTED_PROXY_HOPS = int(
    os.environ.get(
        "BHARATNXT_TRUSTED_PROXY_HOPS",
        "1",
    )
)


# Trusted reverse proxy addresses.
# Only these hosts may provide X-Real-IP (xrealip mode).
TRUSTED_PROXY_IPS = [
    "127.0.0.1",
    "::1",
]

if IS_PRODUCTION:
    TRUSTED_PROXY_IPS = [
        ip.strip()
        for ip in os.environ.get(
            "BHARATNXT_TRUSTED_PROXIES",
            "127.0.0.1,::1"
        ).split(",")
        if ip.strip()
    ]


# ---------------------------------------------------------
# Email
#
# This toolkit sends no email at all - there is no send_mail,
# EmailMessage or mail_admins call anywhere in the codebase.
#
# Django's deploy check (mail.E001) rejects every non-SMTP
# backend, so production uses the dummy backend and silences
# that one check with the justification above.
#
# If email is ever added, switch BACKEND to the SMTP backend,
# configure the host from the environment, and remove
# "mail.E001" from SILENCED_SYSTEM_CHECKS.
# ---------------------------------------------------------

if IS_PRODUCTION:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.dummy.EmailBackend",
        },
    }

    # security.W005 - HSTS includeSubDomains: the toolkit is served from a
    #   bare internal IP address, which has no subdomains.
    # security.W021 - HSTS preload: the browser preload list does not accept
    #   IP addresses, only registrable domains.
    # Both are genuinely not applicable to this deployment. Everything else
    # is left un-silenced so a real new warning stands out.
    SILENCED_SYSTEM_CHECKS = [
        "mail.E001",
        "security.W005",
        "security.W021",
    ]


# ---------------------------------------------------------
# Django's built-in admin
#
# The built-in admin gives direct model access, including the
# User model, so it is not left on the guessable default path
# in production. Set BHARATNXT_DJANGO_ADMIN_PATH to something
# unguessable, or to an empty string to remove it entirely -
# the custom Admin Centre covers day-to-day administration.
#
# The resolved path is also added to the Admin Centre's
# protected prefixes (see accounts/portal_access.py) so the
# same role rules apply to it.
# ---------------------------------------------------------

DJANGO_ADMIN_PATH = os.environ.get(
    "BHARATNXT_DJANGO_ADMIN_PATH",
    "admin/",
).strip().strip("/")

if DJANGO_ADMIN_PATH:
    DJANGO_ADMIN_PATH = f"{DJANGO_ADMIN_PATH}/"


# ---------------------------------------------------------
# Login brute-force protection
#
# Failures are counted per username and per client IP by
# accounts/login_throttle.py.
#
# The counters live in the cache, so production must use a
# cache shared by every gunicorn worker - the default
# per-process LocMemCache would multiply the effective limit
# by the worker count. The database cache needs no extra
# service; create its table once with:
#
#     manage.py createcachetable
# ---------------------------------------------------------

LOGIN_MAX_FAILED_ATTEMPTS = int(
    os.environ.get(
        "BHARATNXT_LOGIN_MAX_ATTEMPTS",
        "5",
    )
)

LOGIN_LOCKOUT_SECONDS = int(
    os.environ.get(
        "BHARATNXT_LOGIN_LOCKOUT_SECONDS",
        str(15 * 60),
    )
)

if IS_PRODUCTION:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "bharatnxt_cache",
        }
    }


# ---------------------------------------------------------
# Platform health check
#
# The hosting platform polls this path from inside its own
# network, so it is exempt from the office IP allow-list.
# It returns a bare "ok" and nothing else.
# ---------------------------------------------------------

HEALTH_CHECK_PATH = os.environ.get(
    "BHARATNXT_HEALTH_CHECK_PATH",
    "/healthz/",
)


# ---------------------------------------------------------
# Persistent data root
#
# Everything the app writes and must keep lives here:
# scheme flyers, pre-import database snapshots, and logs.
#
# On a self-hosted server the project directory is durable,
# so this can stay unset.
#
# On a managed platform the container filesystem is WIPED on
# every deploy and restart. BHARATNXT_DATA_ROOT must point at
# a mounted persistent disk there, or uploaded scheme flyers
# are permanently lost on the next deploy - silently, because
# only the files disappear while their database rows remain.
# ---------------------------------------------------------

DATA_ROOT = os.environ.get(
    "BHARATNXT_DATA_ROOT",
    "",
).strip()

if DATA_ROOT:
    _data_root = Path(DATA_ROOT)

    BNW_PRIVATE_UPLOAD_ROOT = _data_root / "private_uploads"
    BNW_IMPORT_BACKUP_ROOT = _data_root / "audit"
    DEFAULT_LOG_DIR = _data_root / "logs"

else:
    BNW_PRIVATE_UPLOAD_ROOT = BASE_DIR / "private_uploads"
    BNW_IMPORT_BACKUP_ROOT = (
        BASE_DIR / "confidential_source" / "audit"
    )
    DEFAULT_LOG_DIR = BASE_DIR / "logs"


# ---------------------------------------------------------
# Logging
#
# With DEBUG = False an unhandled exception renders a blank
# 500 page and, without this block, vanishes silently.
#
# Everything goes to stdout (captured by journald via the
# gunicorn unit) and to a rotating file for grepping on the
# server.
# ---------------------------------------------------------

LOG_DIR = Path(
    os.environ.get(
        "BHARATNXT_LOG_DIR",
        DEFAULT_LOG_DIR,
    )
)

LOG_DIR.mkdir(parents=True, exist_ok=True)

LOG_LEVEL = os.environ.get(
    "BHARATNXT_LOG_LEVEL",
    "INFO" if IS_PRODUCTION else "DEBUG",
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": (
                "{asctime} {levelname} {name} "
                "{process:d} {message}"
            ),
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "bharatnxt.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 10,
            "encoding": "utf-8",
            "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console", "file"],
        "level": LOG_LEVEL,
    },

    "loggers": {
        # Unhandled view exceptions and 4xx/5xx responses.
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
        # Blocked-network hits, failed logins, import failures.
        "accounts": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "toolkit": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
